web:
    # build: ./docker/web
    image: hqjbest/php7.1-apache
    container_name: 1024_web
    ports:
        - "9980:80"
    expose:
        - "80"
    volumes:
        - ./:/var/www/html
        - ./docker/web/vhosts/:/etc/apache2/sites-enabled/
    links:
        - mysql
        - redis
    environment:
        - TERM=xterm-256color
    extra_hosts:
      - "backend.1024.local:127.0.0.1"
      - "api.1024.local:127.0.0.1"
mysql:
    # build: ./docker/mysql
    image: mysql:5.6
    container_name: 1024_mysql
    volumes:
        - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
        - "9307:3306"
    expose:
        - "3306"
    environment:
        MYSQL_ROOT_PASSWORD: 1024
        MYSQL_DATABASE: 1024
        MYSQL_USER: 1024
        MYSQL_PASSWORD: 1024
redis:
    # image: redis
    image: redis:3.2
    container_name: 1024_redis
    ports:
        - "9379:6379"
    volumes:
     - ./:/var/www/html/docker/web/